### PR TITLE
Fix #93 context deadline exceeded

### LINKED ISSUE #93: Handle "context deadline exceeded" when fetching build logs
In https://releng.netbsd.org/bulktracker/pkg/51882393, the build log reliably fails to display because there is a timeout fetching the report. This is what it looks like:

Image

This could be handled differently somehow. Maybe a friendlier message?

### PR DESCRIPTION
**Pull request by acirep**
Increased timeout from 2 to 3 seconds and added more friendly error message in case of "context deadline exceeded" error (timeout).

@bsiegert please review and tests if possible, it passed my local tests.

### CODE REVIEW

File: templates/templates.go [hunk 1]
```diff
@@ -196,15 +196,23 @@ func PkgInfo(w io.Writer, res ddao.GetSingleResultRow) {
 			req, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
 			if err != nil {
 				results[index].StatusCode = http.StatusInternalServerError
-				results[index].Error = err.Error()
+				if err == context.DeadlineExceeded {
```
Comment (bsiegert) [inline templates/templates.go:199]: This should be `errors.Is`.

File: templates/templates.go [hunk 2]
```diff
@@ -196,15 +196,23 @@ func PkgInfo(w io.Writer, res ddao.GetSingleResultRow) {
...
+				}
 				return
 			}
 
 			// Make the request
 			resp, err := http.DefaultClient.Do(req)
 			if err != nil {
 				results[index].StatusCode = http.StatusInternalServerError
-				results[index].Error = err.Error()
+				if err == context.DeadlineExceeded || err.Error() == "context deadline exceeded" {
```
Comment (bsiegert) [inline templates/templates.go:211]: I think that with `errors.Is`, the second clause won't be needed, as this will fire even for a wrapped DeadlineExceeded.

**Review by bsiegert — APPROVED** [review]
Thank you for your contributions!

My comment is just a tiny nit. I'll merge and make the change myself if that's okay.
