### PR TITLE
Fetch build stages data while building pkg_info page

### LINKED ISSUE #75: Spurious links to configure/build/install stages
At a failed package build result page like https://releng.netbsd.org/bulktracker/pkg/46786788, there are links to each stage's logs: [work](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/work.log), [pre-clean](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/pre-clean.log), [checksum](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/checksum.log), [depends](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/depends.log), [configure](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/configure.log), [build](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/build.log), [install](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044//mysql-cluster-7.5.25nb9/install.log).

But since the configure stage failed, the build and install log links are 404.

In the [original bulk build report](https://us-central.manta.mnx.io/pkgsrc/public/reports/Linux/el8/trunk/x86_64/20250111.1044/meta/report.html), the links end at configure -- it doesn't present build or install links to oblivion.

It would be nice if the bulktracker did the same -- for a while I thought that bulk results had just been taken down unreasonably soon after the reports were posted, before I realized some stage before install had been failing in all the results I was looking into from the bulktracker page.

Unfortunately it looks like this might require cooperation from pbulk, since it looks like pbulk's create-report-html.awk relies on file existence tests rather than on the content of the report.

### LINKED ISSUE #88: iframe log viewer does not show if content is on HTTP
@acirep Maybe you have an idea.

Looking at https://releng.netbsd.org/bulktracker/pkg/48882119, the iframe content never loads, both in Chrome and in Firefox. 

In the JS console, I found this error:

> Mixed Content: The page at 'https://releng.netbsd.org/bulktracker/pkg/48882119' was loaded over HTTPS, but requested an insecure frame 'http://shadow.netbsd.org/pub/pkgsrc/packages/reports/HEAD/NetBSD-10.0-x86_64/20250319.0442/xmh-1.0.5/configure.log'. This request has been blocked; the content must be served over HTTPS.

This seems like a fairly fundamental limitation of the iframe approach.

And shadow.netbsd.org does not do https, unfortunately.

### PR DESCRIPTION
**Pull request by acirep**
Added simple go routine that fetches in parallel all build stages data while pkg_info page is being built. This solves #88 and #75.

Buttons that are pointing to log files (buiild stages) that don't exist (404) are now disabled. :tada:  HTTP status codes are also captured and available for future improvements if we would like to style output further and highlight errors or similar. :bulb: 

For security and stability reasons `iframe` is replaced with `pre` HTML element. Additionally added link to original log location instead of Go button to make it more visible to the users where the log file is and what are they navigating to. In case this URL is too long, middle of URL is shortened and replaced with ` ... `.

Additionally, CSS and JS code is extracted in external CSS and JS files :tada: 

@bsiegert , please review - all feedback welcome!

### CODE REVIEW

File: templates/templates.go [hunk 1]
```diff
@@ -140,15 +143,92 @@ func BulkBuildInfo(w io.Writer, b *ddao.Build) {
...
+	}
+
+	// Create results slice
+	results := make([]URLRequestResult, len(stages))
+
+	// Create a WaitGroup to wait for all goroutines
+	var wg sync.WaitGroup
+	wg.Add(len(stages))
+
+	// Create a context with a 10-second timeout
```
Comment (bsiegert) [inline templates/templates.go]: 10 seconds is probably too much. Maybe 2 seconds?

File: templates/templates.go [hunk 2]
```diff
@@ -140,15 +143,92 @@ func BulkBuildInfo(w io.Writer, b *ddao.Build) {
...
+			body, err := io.ReadAll(resp.Body)
+			if err != nil {
+				results[index].StatusCode = resp.StatusCode
+				results[index].Error = err.Error()
+				return
+			}
+
+			// Store the result
+			results[index].StatusCode = resp.StatusCode
+			results[index].Data = string(body)
```
Comment (bsiegert) [inline templates/templates.go:222]: I am concerned about very large build log files. Can you add some truncation? Say, if size over 1 MB, only return the last MB and a "[truncated]" message at the beginning.

File: templates/templates.go [hunk 3]
```diff
@@ -213,3 +293,12 @@ func SentinelsInit(w io.Writer, selector string, apiName string, number int64) {
 		Number:   number,
 	})
 }
+
+// URLRequestResult represents the result of a URL request
```
Comment (bsiegert) [inline templates/templates.go]: nit: . at end of line, doc comments should be full sentences

File: templates/pkg_info.html [hunk 4]
```diff
@@ -20,105 +20,58 @@
...
-          <button id="toggleFullscreen" class="btn btn-sm btn-default pull-right">
-             &#x26F6; Fullscreen
-          </button>
-          <button id="go" class="btn btn-sm pull-right">
-             Go
-          </button>
+        <dt>Build Logs</dt>
+        <script>
+          // Create JavaScript object with URLData
+          var urlData = {
```
Comment (bsiegert) [inline templates/pkg_info.html]: Instead of constructing JSON inline like this, can you add a template function that calls `json.Marshal` for the whole data structure?

File: templates/templates.go [hunk 5]
```diff
@@ -140,15 +143,92 @@ func BulkBuildInfo(w io.Writer, b *ddao.Build) {
...
+	}
+
+	// Wait for all requests to complete
+	wg.Wait()
+
+	// Create the structure to pass to the template
 	s := struct {
-		Res *ddao.GetSingleResultRow
+		Res     *ddao.GetSingleResultRow
+		URLData []URLRequestResult
```
Comment (bsiegert) [inline templates/templates.go]: Doesn't need to be in this PR but: what do you think about a cache for `URLData` with a relatively short duration?

**Review by bsiegert — CHANGES_REQUESTED** [review]
Hi @acirep, sorry for taking so long to review this. I have a few comments, but this is pretty nice otherwise.

File: templates/templates.go (hunk 2 above)
Comment (acirep) [reply templates/templates.go:222]: Hmmm is this really an issue? If web servers do they job, like they should, content is gzipped. These pure text files will be heavily compressed and data transfer size is going to be just a tiny fraction of the original file size. What do you think? Maybe I'm missing something?

File: templates/pkg_info.html (hunk 4 above)
Comment (acirep) [reply templates/pkg_info.html]: Actually I did try this initially but due to marshaling object to string, everything was marshalled with quotes and in JS land it should be keys without quotes. So things get complex rather quickly and I did not find elegant solution for this - this is why I went with this more "brute force" approach.

if you have ideas how to do this nicely please let me know!

File: templates/templates.go (hunk 5 above)
Comment (acirep) [reply templates/templates.go]: Absolutely! I think this should be indeed separate PR where we revisit this cache application wide and see where it makes sense to use it.

File: templates/templates.go (hunk 2 above)
Comment (acirep) [reply templates/templates.go:222]: Here is an example where we see that for sure all content is gzipped by the web server and compression ratio is actually very good, from almost 120kB it goes down to bit less than 4kB

Screenshot From 2025-04-07 20-56-40

This is one of the actual `work.log` files for gtk3, granted these can be way bigger than 120kB but with compression we should be good as text files compress quite nicely.

File: templates/pkg_info.html (hunk 4 above)
Comment (bsiegert) [reply templates/pkg_info.html]: AIUI, keys with quotes are perfectly legal JS.

```JS
>> a = {a: 'b'}
Object { a: "b" }

>> a = {"a": "b"}
Object { a: "b" }
```

File: templates/templates.go (hunk 2 above)
Comment (bsiegert) [reply templates/templates.go:222]: OK, we can always do this later.

File: templates/pkg_info.html (hunk 4 above)
Comment (acirep) [reply templates/pkg_info.html]: Ah! I see, will try again when I wrap up vacation 🙌 👍

Comment (acirep) [reply templates/pkg_info.html]: @bsiegert , this is now implemented with the latest commit

**Review by bsiegert — APPROVED** [review]

**Comment by bsiegert** [comment]
Thanks for bearing with me :) I just approved and merged this.

**Comment by acirep** [comment]
> Thanks for bearing with me :) I just approved and merged this.

Nice! :+1:  No worries, I really appreciate feedback and ideas so don't hesitate in the future to brainstorm with me!
